### ISSUE TITLE
Crash when placing LCDs

### ISSUE THREAD

**Issue by mkaito** [0x00002a/AdjustableLCDs#1]
This is from the SE logs, let me know if there's anything else I can get you.

```
Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Natomic.AngledLCDs.TerminalHelper.<>c__DisplayClass8_0`1.<AddTermSlider>b__0(IMyTerminalBlock b)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.OnUpdateVisual()
   at Sandbox.Game.Gui.MyTerminalControl`1.UpdateVisual()
   at Natomic.AngledLCDs.TerminalHelper.RefreshAll()
   at Natomic.AngledLCDs.AngledLCD`1.UpdateOnceBeforeFrame()
   at VRage.Game.Components.MyGameLogicComponent.VRage.Game.Entity.EntityComponents.Interfaces.IMyGameLogicComponent.UpdateOnceBeforeFrame(Boolean entityUpdate)
   at VRage.Game.Entity.MyGameLogic.UpdateOnceBeforeFrame()
   at VRage.Game.Entity.MyGameLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

**Comment by 0x00002a** [comment]
Thanks for the report. Is this in multiplayer?

**Comment by mkaito** [comment]
No, in single player.

**Comment by cjbehm** [comment]
Just came to report the same, with the same stack trace and also single player.

It was repeatable; I ground down a Wide LCD and went to place it again in another location and that's when it crashes.

```
2022-01-26 22:06:55.694 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Natomic.AngledLCDs.TerminalHelper.<>c__DisplayClass8_0`1.<AddTermSlider>b__0(IMyTerminalBlock b)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.OnUpdateVisual()
   at Sandbox.Game.Gui.MyTerminalControl`1.UpdateVisual()
   at Natomic.AngledLCDs.TerminalHelper.RefreshAll()
   at Natomic.AngledLCDs.AngledLCD`1.UpdateOnceBeforeFrame()
   at VRage.Game.Components.MyGameLogicComponent.VRage.Game.Entity.EntityComponents.Interfaces.IMyGameLogicComponent.UpdateOnceBeforeFrame(Boolean entityUpdate)
   at VRage.Game.Entity.MyGameLogic.UpdateOnceBeforeFrame()
   at VRage.Game.Entity.MyGameLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

**Comment by 0x00002a** [comment]
OK I've reproduced it, thanks for the reports. I'll hopefully have a fix out this evening or tomorrow

**Comment by 0x00002a** [comment]
Alright I've pushed an update which should fix this, let me know and I'll close the issue

**Comment by mkaito** [comment]
I can no longer reproduce. I'll let you know if it happens again.

Thanks!
