### ISSUE TITLE
Repeated crash on dedicated server with NPC mods

### ISSUE THREAD

**Issue by obfuscode** [0x00002a/AdjustableLCDs#3]
Hello, playing on a dedicated GTX server (not Torch) I had multiple crashes when NPC ships would load into my proximity.

The two NPC grids that triggered it are:
`grid (NPC-PLX) Heroes Pride` (Parallax Concepts mod, 1 crash so far)
`grid (NPC-TOC) GSX-5010 Chrono-Station` (Trade Operators Coalition mod, x2 crashes)

We also have Imber Corporation mod installed but I don't think I've been close enough to them to see if it triggers a crash.

I believe this is repeatable as it crashed twice for the same station.

The error message was the same for all 3 crashes and is as follows:
```
2023-10-23 20:46:16.492 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Natomic.AngledLCDs.TerminalHelper.<>c__6`1.<AddTermBtn>b__6_0(IMyTerminalBlock b)
   at Natomic.AngledLCDs.AngledLCD`1.<>c__DisplayClass71_0.<AddEnabled>b__0(IMyTerminalBlock b)
   at Sandbox.Game.Gui.MyTerminalControl`1.OnUpdateVisual()
   at Sandbox.MySandboxGame.ProcessInvoke(Boolean isClosing)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2023-10-23 20:46:16.493 - Thread:   1 ->  Showing message
2023-10-23 20:46:18.921 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_203_024
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 1225
PCUCount: 20543
IsHang: False
GCMemory: 4390
GCMemoryAllocated: 4390
HWAvailableMemory: 13361
ProcessPrivateMemory: 23179
AnalyticId: SE
```

Thank you for this amazing mod! I hope you're able to get it fixed because this is such a great addition to the game!

**Comment by 0x00002a** [comment]
Hum that's weird I thought I fixed all those in that area. Ok I'll look into it

**Comment by 0x00002a** [comment]
published a new version, I haven't actually reproduced the issue but I've spotted what the problem might be. If it isn't fixed please let me know and if possible provide a link to a world that reproduces it (preferbly on load but otherwise a creation link that crashes on spawn)

**Comment by obfuscode** [comment]
Great! I'll give this a test later. The server I was on removed the mod because of the crashes so I don't know if testing it on another server will produce the same circumstances of the crash but I'll give it a try.
